- hosts: 172.31.40.244
  become: yes
  tasks:
    - name: install java
      apt:
        name: openjdk-8-jdk
        state: present 
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start the service 
      service: 
      name: apache2
        state: started
        enabled: yes
