- hosts: localhost
  become: yes
  tasks:
    - name: install java
      apt:
        name: openjdk-8-jdk
        state: present 
    - name: install tomcat7
      apt:
        name: tomcat7
        state: present
    - name: download file
      get_url: 
        url: https://golwf.s3.us-east-2.amazonaws.com/gameoflife.war
        dest: /var/lib/tomcat7/webapps/gameoflife.war
    - name: start the service 
      service: 
      name: tomcat7
        state: started
        enabled: yes
